fix vite esm-bundler compilation error
To use `<app>` directly in a blade component, we need to use the vue esm bundler. There's a compilation error related to vue demi:

```
10:56:19 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/vue-demi/lib/index.mjs:1:16: ERROR: Could not read from file: /Users/johnsojr/code/bluesheet/vue/dist/vue.esm-bundler.js
```

It may or may not be directly related to vue-demi, but vue-demi can be removed after the update to vue3. AND we only need the `<App>` component in the blade template.

So, instead, we have the `new Vue` just render the `<App>` component directly at <div id="app"></app>, so we don't need to use any vue components within the blade templates.